export const ABOUT_ROUTE = '/about'
export const VACANCY_DETAILS_ROUTE = '/vacancy'
export const HOME_ROUTE = '/'
export const VACANCIES_LIST_ROUTE = '/vacancies'
export const CONTACTS_ROUTE = '/contacts'
export const NEWS_ROUTE = '/news'